dist: bionic
os: linux
language: python
python:
  - "3.8"
virtualenv:
  system_site_packages: true

addons:
    apt:
        packages:
            - dstat
before_install:
    - echo hi
install:
    - pip3 install .
    - pip3 install codecov
jobs:
  allow_failures:
  - rvm: 1.9.3
  exclude:
  - rvm: 1.9.3
    gemfile: gemfiles/Gemfile.rails-2.3.x
    env: ISOLATED=true
  - rvm: jruby
    gemfile: gemfiles/Gemfile.rails-2.3.x
    env: ISOLATED=true
script: 
  - sudo python3 ./src/smacli/test.py
  - coverage run ./src/smacli/test.py
# Push the results back to codecov
after_success:
  - codecov
branches:
  only:
  - master
  - stable