dist: bionic
os: linux
language: python
sudo: required
python:
  - "3.6"
virtualenv:
  system_site_packages: true

  # command to install dependencies
addons:
    apt:
        packages:
            - dstat
before_install:
    - echo hi
install:
    - pip3 install .
matrix:
  allow_failures:
  - rvm: 1.9.3
script: sudo python3 ./src/smacli/test.py

branches:
  only:
  - master
  - stable
matrix:
  exclude:
  - rvm: 1.9.3
    gemfile: gemfiles/Gemfile.rails-2.3.x
    env: ISOLATED=true
  - rvm: jruby
    gemfile: gemfiles/Gemfile.rails-2.3.x
    env: ISOLATED=true