
  # After registering a name on build.snapcraft.io, commit an uncommented line:
  name: smacom
  type: app
  base: os
  version: '1.0.3' # just for humans, typically '1.2+git' or '1.3.2'
  summary: snap pkg for smacom by Microbot Systems, Inc. # 79 char long summary
  description: |    
    This pkg intended for business intellegance solutions @Microbot Systems, Inc.
    Be aware of contributing open source projects that they're offered as-is,
    without warranty, and disclaiming liability for damages resulting from using the pkg.
    

  grade: devel # must be 'stable' to release into candidate/stable channels
  confinement: devmode # use 'strict' once you have the right plugs and slots

  parts:
    my-part:
      # See 'snapcraft plugins'
      plugin: nil
  
